package com.productivitybandits.focuspocusapp.models

data class Nudge(
    val id: String,           // Unique ID (generated by backend)
    val title: String,        // Title of the nudge
    val description: String,  // Optional description
    val isCompleted: Boolean  // True if user has completed it
)

// 🧠 Data model representing a single Nudge
// Used across API calls, UI rendering, and ViewModel state